version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-express
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Minden09
      - MSSQL_PID=Express  # Setzt die Edition auf Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql  # Persistiert die Daten

volumes:
  mssql_data:
    driver: local
